asistPatentCore.Web/Controllers/AuthorizedUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using asistPatentCore.Service.IConstractor;
using asistPatentCore.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace asistPatentCore.Web.Controllers
{
    public class AuthorizedUserController : Controller
    {
        private readonly IDefaultValuesService _defaultValuesService;
        private readonly ICookieService _cookieService;
        private readonly IAuthorizedUserService _authorizedUserService;
        private readonly IUsersService _usersService;
        public AuthorizedUserController(IUsersService usersService, IDefaultValuesService defaultValuesService, ICookieService cookieService, IAuthorizedUserService authorizedUserService)
        {
            _usersService = usersService;
            _defaultValuesService = defaultValuesService;
            _cookieService = cookieService;
            _authorizedUserService = authorizedUserService;
        }
        [Route("~/hesabim/yetkililer")]
        public IActionResult Index()
        {
            if (!_cookieService.checkUserLogin())
            {
                return Redirect("~/giris");
            }
            return View(_authorizedUserService.getAuthorizedUserList(_usersService.getUserInformation(_cookieService.getSessionEmail()).userId));
        }
        [Route("~/hesabim/yetkililer/{authId}")]
        public IActionResult Detail(Guid authId)
        {
            if (!_cookieService.checkUserLogin())
            {
                return Redirect("~/giris");
            }
            return View(_authorizedUserService.detailAuthorizedUser(authId, _usersService.getUserInformation(_cookieService.getSessionEmail()).userId));
        }
        [HttpPost]
        [Route("~/hesabim/yetkililer/{authId}")]
        public IActionResult Detail(UsersViewModel model)
        {
            if (!_cookieService.checkUserLogin())
            {
                return Redirect("~/giris");
            }
            if (_authorizedUserService.updateAuthorizedUser(model, _usersService.getUserInformation(_cookieService.getSessionEmail()).userId))
                return View(model);
            else
                return Redirect("~/hesabim/yetkililer/"+model.authId);
        }
        [Route("~/hesabim/yetkililer/yeni")]
        public IActionResult Create()
        {
            if (!_cookieService.checkUserLogin())
            {
                return Redirect("~/giris");
            }
            return View(new UsersViewModel());
        }
        [HttpPost]
        [Route("~/hesabim/yetkililer/yeni")]
        public IActionResult Create(UsersViewModel model)
        {
            if (!_cookieService.checkUserLogin())
            {
                return Redirect("~/giris");
            }
            if (!_authorizedUserService.addAuthorizedUser(model, _usersService.getUserInformation(_cookieService.getSessionEmail()).userId))
            {
                return View(model);
            }
            return Redirect("~/hesabim/yetkililer");
        }
        [Route("~/hesabim/yetkili-sil/{authId}")]
        public IActionResult Delete(Guid authId)
        {
            if (!_cookieService.checkUserLogin())
            {
                return Redirect("~/giris");
                
            }
            if(!_authorizedUserService.deleteAuthorizedUser(authId, _usersService.getUserInformation(_cookieService.getSessionEmail()).userId))
            {
                return Redirect("~/hesabim/yetkililer/" + authId);
            }
            return Redirect("~/hesabim/yetkililer");
        }
    }
}

asistPatentCore.Web/Views/AuthorizedUser/Create.cshtml
@model asistPatentCore.ViewModel.UsersViewModel
@{
    ViewBag.title = "Asist Patent | Yeni Yetkili oluştur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">
                        Yeni Yetkili oluştur
                    </h4>


                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                @using (Html.BeginForm("Create", "AuthorizedUser", FormMethod.Post))
                                {

                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label">Ad</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userName, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Soyad</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userSurname, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Telefon numarası</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userPhoneNumber, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">E-Mail Adresi</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userEmailAdress, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>

                                    <button class="btn float-right btn-custom-asist " type="submit">Oluştur</button>

                                }
                            </div>
                        </div>

                    </div>
                    <!-- end row -->

                </div> <!-- end card-box -->
            </div><!-- end col -->
        </div>
    </div><!-- end col -->
</div>
<!-- end row -->

asistPatentCore.Web/Views/AuthorizedUser/Detail.cshtml
@model asistPatentCore.ViewModel.UsersViewModel
@{
    ViewBag.title = "Asist Patent | Yetkili kişiler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">
                        Yeni Yetkili oluştur
                    </h4>


                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                @using (Html.BeginForm("Detail", "AuthorizedUser", FormMethod.Post))
                                {

                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label">Ad</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userName, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Soyad</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userSurname, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Telefon numarası</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userPhoneNumber, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">E-Mail Adresi</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.userEmailAdress, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>

                                    <button class="btn float-right btn-custom-asist " type="submit">Güncelle</button>
                                    <a href="~/hesabim/yetkili-sil/@Model.authId" class="btn float-right btn-danger m-r-10"> <i class="fa fa-user-times"></i> Sil</a>

                                }
                            </div>
                        </div>

                    </div>
                    <!-- end row -->

                </div> <!-- end card-box -->
            </div><!-- end col -->
        </div>
    </div><!-- end col -->
</div>
<!-- end row -->

asistPatentCore.Web/Views/AuthorizedUser/Index.cshtml
@using asistPatentCore.Model.Enums
@model asistPatentCore.ViewModel.UsersListViewModel
@{
    ViewBag.title = "Asist Patent | Yetkililer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Start Page content -->
<div class="content">
    <div class="container-fluid">

        <div class="row">
            
            <div class="col-12">

                <div class="card-box">
                    <div class="form-group row">
                        <div class="col-12">
                            <div class="form-group text-left m-b-0 pt-3">
                                <a href="~/hesabim/yetkililer/yeni" class="btn btn-custom-asist">Yeni Yetkili Ekle</a>
                            </div>
                        </div>
                    </div>
                    <div class="table-rep-plugin">
                        <div class="table-responsive" data-pattern="priority-columns">
                            <table id="tech-companies-1" class="table  table-striped">
                                <thead>
                                    <tr>
                                        <th>Ad </th>
                                        <th>Soyad</th>
                                        <th>Cep Telefonu </th>
                                        <th>E-mail Adresi</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model.userList)
                                    {

                                        <tr>
                                            <th>@item.userName</th>
                                            <td>@item.userSurname</td>
                                            <th>@item.userPhoneNumber</th>
                                            <td>@item.userEmailAdress</td>
                                            <td><a href="~/hesabim/yetkililer/@item.authId" class="btn btn-outline-success waves-light waves-effect">Detay</a></td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>

                </div>
            </div>
        </div>
        <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->