asistPatentCore.Web/Controllers/MailSourcesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using asistPatentCore.Web.Models;
using asistPatentCore.ViewModel;
using asistPatentCore.Service.IConstractor;
using asistPatentCore.Service;

namespace asistPatentCore.Web.Controllers
{
    public class MailSourcesController : Controller
    {
        private readonly IEmailService  _emailService;
        private readonly ICookieService _cookieService;

        public MailSourcesController(IEmailService emailService, ICookieService cookieService)
        {
            _cookieService = cookieService;
            _emailService = emailService;
        }
        [Route("~/admin/mail-kaynaklari")]
        public IActionResult Index()
        {
            if (!_cookieService.checkAdminState(Model.Enums.UserRoleEnum.supervisor))
            {
                return Redirect("~/anasayfa");
            }
            return View(_emailService.getMailSourceList());
        }
        [Route("~/admin/mail-kaynaklari/{id:int}")]
        public IActionResult Detail(int id)
        {
            if (!_cookieService.checkAdminState(Model.Enums.UserRoleEnum.supervisor))
            {
                return Redirect("~/anasayfa");
            }
            return View(_emailService.getMailSourceDetail(id));
        }
        [HttpPost]
        [Route("~/admin/mail-kaynaklari/{id:int}")]
        public IActionResult Detail(MailSourceViewModel model)
        {
            if (!_cookieService.checkAdminState(Model.Enums.UserRoleEnum.supervisor))
            {
                return Redirect("~/anasayfa");
            }
            if (_emailService.updateMailSource(model))
                return View(model);
            else
                return Redirect("~/admin/mail-kaynaklari/"+model.id);
            
        }
        [Route("~/admin/mail-kaynaklari/yeni")]
        public IActionResult Create()
        {
            if (!_cookieService.checkAdminState(Model.Enums.UserRoleEnum.supervisor))
            {
                return Redirect("~/anasayfa");
            }
            return View(new MailSourceViewModel());
        }
        [HttpPost]
        [Route("~/admin/mail-kaynaklari/yeni")]
        public IActionResult Create(MailSourceViewModel model)
        {
            if (!_cookieService.checkAdminState(Model.Enums.UserRoleEnum.supervisor))
            {
                return Redirect("~/anasayfa");
            }
            if (_emailService.createMailSource(model))
            {
                return Redirect("~/admin/mail-kaynaklari");
            }
            return View(model);
        }
    }
}

asistPatentCore.Web/Views/MailSources/Create.cshtml
@model asistPatentCore.ViewModel.MailSourceViewModel
@{
    ViewBag.title = "Asist Patent | Email Kaynak Oluştur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">
                        Yeni Mail Adresi
                    </h4>


                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                @using (Html.BeginForm("Create", "MailSources", FormMethod.Post))
                                {
                                    
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label">Email Adı</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.username, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Email Parola</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.password, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Sunucu</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.smtpServer, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Port</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.port, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Gönderen Adı</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.displayName, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">SSL Aktifliği</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.CheckBoxFor(m => m.enableSsl)
                                        </div>
                                    </div>
                                    <button class="btn float-right btn-custom-asist " type="submit">Ekle</button>

                                }
                            </div>
                        </div>

                    </div>
                    <!-- end row -->

                </div> <!-- end card-box -->
            </div><!-- end col -->
        </div>
    </div><!-- end col -->
</div>
<!-- end row -->

asistPatentCore.Web/Views/MailSources/Detail.cshtml
@model asistPatentCore.ViewModel.MailSourceViewModel
@{
    ViewBag.title = "Asist Patent | Email Kaynak Detay Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="container-fluid">

        <div class="row">
            <div class="col-12">
                <div class="card-box">
                    <h4 class="m-t-0 header-title">
                        Mail Düzenleyici
                    </h4>


                    <div class="row">
                        <div class="col-12">
                            <div class="p-20">
                                @using (Html.BeginForm("Detail", "MailSources", FormMethod.Post))
                                {
                                    @Html.HiddenFor(m => m.id);

                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label">Email Adı</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.username, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Email Parola</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.password, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Sunucu</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.smtpServer, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Port</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.port, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">Gönderen Adı</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.TextBoxFor(m => m.displayName, new { @class = "form-control", @required = "required" })
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-md-2 col-sm-12 col-xs-12 col-form-label" for="example-email">SSL Aktifliği</label>
                                        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                                            @Html.CheckBoxFor(m => m.enableSsl)
                                        </div>
                                    </div>
                                    <button class="btn float-right btn-custom-asist " type="submit">Bilgileri Güncelle</button>

                                }
                            </div>
                        </div>

                    </div>
                    <!-- end row -->

                </div> <!-- end card-box -->
            </div><!-- end col -->
        </div>
    </div><!-- end col -->
</div>
<!-- end row -->

asistPatentCore.Web/Views/MailSources/Index.cshtml
@using asistPatentCore.Model.Enums
@model asistPatentCore.ViewModel.MailSourceListViewModel
@{
    ViewBag.title = "Asist Patent | Email Kaynak Listesi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Start Page content -->
<div class="content">
    <div class="container-fluid">

        <div class="row">
            
            <div class="col-12">
                <div class="card-box">
                    <a href="~/admin/mail-kaynaklari/yeni" class="btn m-b-10 btn-custom-asist " type="submit">Yeni Oluştur</a>
                    <div class="table-rep-plugin">
                        <div class="table-responsive" data-pattern="priority-columns">
                            <table id="tech-companies-1" class="table  table-striped">
                                <thead>
                                    <tr>
                                        <th>Mail Adresi</th>
                                        <th>Sunucu</th>
                                        <th>Port</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model.mailList)
                                    {

                                        <tr>
                                            <th>@item.username</th>
                                            <td>@item.smtpServer</td>
                                            <td>@item.port</td>
                                            <td><a href="~/admin/mail-kaynaklari/@item.id" class="btn btn-outline-success waves-light waves-effect">Değiştir</a></td>

                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>

                    </div>

                </div>
            </div>
        </div>
        <!-- end row -->

    </div> <!-- container -->

</div> <!-- content -->